### ISSUE TITLE
Création de la structure de la base de donnée (SqLite)

### ISSUE THREAD

**Issue by TChriste** [TChriste/FinanceManager#1]

**Comment by TChriste** [comment]
Proposition de structure : 

**Table Comptes :** 
- id
- libelle
- solde

**Table Categories :** 
- id
- libelle

**Tables Transactions :** 
- id
- compteId
- categorieId
- montant

**Comment by AlessMonda** [comment]
Commit : 0971c4915caea8a653ab21fccc9eeac022c62a0d
